<#
.SYNOPSIS
    Initializes Git + Git LFS in an existing Unity project folder, with a
    Unity-appropriate .gitignore and .gitattributes for binary assets.

.USAGE
    Run this FROM INSIDE the Unity project root (the folder containing Assets\).
    .\2-init-git.ps1
#>

if (-not (Test-Path ".\Assets")) {
    Write-Host "No Assets\ folder found here. Run this from inside the Unity project root." -ForegroundColor Red
    exit 1
}

git init

git lfs install

$gitignore = @"
# Unity generated
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Mm]emoryCaptures/
/[Uu]ser[Ss]ettings/

# Autogenerated VS/Rider/VSCode project files
.vs/
.vscode/
*.csproj
*.unityproj
*.sln
*.suo
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity crash logs
sysinfo.txt

# Builds (tracked separately, not in source control by default)
*.apk
*.aab
*.unitypackage
*.app

# OS files
.DS_Store
Thumbs.db
"@

Set-Content -Path ".\.gitignore" -Value $gitignore -Encoding utf8

$gitattributes = @"
# Git LFS for Unity binary assets
*.psd filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.jpeg filter=lfs diff=lfs merge=lfs -text
*.tga filter=lfs diff=lfs merge=lfs -text
*.gif filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.ogg filter=lfs diff=lfs merge=lfs -text
*.fbx filter=lfs diff=lfs merge=lfs -text
*.blend filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.mov filter=lfs diff=lfs merge=lfs -text
*.anim filter=lfs diff=lfs merge=lfs -text
*.controller filter=lfs diff=lfs merge=lfs -text
"@

Set-Content -Path ".\.gitattributes" -Value $gitattributes -Encoding utf8

git add .gitignore .gitattributes
git commit -m "Initial commit: gitignore + LFS config"

Write-Host ""
Write-Host "Git + Git LFS initialized." -ForegroundColor Green
Write-Host "Next: create the GitHub repo, add it as a remote, and push."
